version: "3"
services:
  postgres:
      container_name: postgres
      restart: always
      image: postgres:latest
      build:
        context: .
        dockerfile: ./PostgresDockerfile
      environment:
          POSTGRES_DB: "vention"
          POSTGRES_HOST_AUTH_METHOD: "trust" # Not recommended, only for demo purposes
      volumes:
          - ./database:/var/lib/postgresql
      ports:
          - "5432:5432"
